spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tourism_db
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer_key: ${JWT_SIGNER_KEY}
  valid_duration: 36000