spring:
  datasource:
    url: jdbc:h2:mem:timeline-dev;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signer_key: ${JWT_SIGNER_KEY:dev-signer-key-with-sufficient-length-for-hs512-0123456789}
  valid_duration: 36000
  refreshable_duration: 604800
