package com.project.backend.modules.notification.enums;

public enum NotificationType {
    WELCOME,
    SYSTEM_ALERT,
    TIMELINE_UPDATED,
    TIMELINE_EVENT_REMINDER,
    SCHEDULED_PLACE_REMINDER,
    OVERLAPPING_SCHEDULE_WARNING,
    COLLABORATION_INVITE,
    COLLABORATOR_EDITED_ITINERARY,
    COLLABORATOR_ADDED_EVENT,
    COLLABORATOR_REMOVED_EVENT,
    MENTION
}
